import type { Task } from './model.js'

// Demo fixture: the REAL JRS + Brightly working state gathered during design
// (statuses live in the vault; the tracker's Status column is a stale seed).
// Used when COCKPIT_DEMO=true so the cockpit renders live in Slack without any
// Google setup. Only the two shared Drive artifacts have real external links;
// vault-only drafts intentionally show "no deliverable linked yet".

const JRS: Task[] = [
  { taskNum: '41', company: 'JRS', title: 'School sourcing — 62 Tucson principals', owner: 'School Sourcing (agent)', status: 'delivered_awaiting', rawStatus: 'delivered - awaiting review', deliverableDriveUrl: 'https://docs.google.com/spreadsheets/d/1-vmzHXk_jt2UJrA8ssLKE_c4PzOoZBEEmasB3jK1ZV0/edit', deliverableTitle: 'JRS — Tucson (TUSD) principals', description: '62 verified Tucson/TUSD principals with emails, ready for outreach.', dependency: 'Your OK to start outreach (#42) · confirm Jason as sender', lastUpdated: '2026-06-29' },
  { taskNum: '65', company: 'JRS', title: 'Testimonials form (live)', owner: 'Agent M42', status: 'delivered_awaiting', rawStatus: 'delivered - awaiting review', deliverableDriveUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSd0KNFTlRlc8CHnBNPGZurq1z2k_MY_dkmNrhkSu0uoRYjDFw/viewform', deliverableTitle: 'JRS — Testimonials request form', description: 'Live Google Form with a privacy choice per response + tracking sheet.', dependency: 'Approve the request emails · supply active-contacts list', lastUpdated: '2026-06-29' },
  { taskNum: '52', company: 'JRS', title: 'Schedule 48 social posts in Metricool', owner: 'Agent M42', status: 'done', rawStatus: 'done', description: '48 posts approved 06-23, scheduled to auto-publish in Metricool.', lastUpdated: '2026-06-23' },
  { taskNum: '40', company: 'JRS', title: 'Fix JRS website positioning', owner: 'Me (Derek)', status: 'in_progress', rawStatus: 'drafting', description: 'Positioning audit + rewritten page-copy recommendations (draft).', dependency: 'Derek/Jason review before the Wix copy goes live', lastUpdated: '2026-06-04' },
  { taskNum: '42', company: 'JRS', title: 'School outreach email sequence', owner: 'Agent M42', status: 'delivered_awaiting', rawStatus: 'awaiting approval', description: '5-email cold-outreach sequence + follow-up schedule, merge-ready.', dependency: 'Jason/Derek read + approve · confirm sender name', lastUpdated: '2026-06-04' },
  { taskNum: '43', company: 'JRS', title: 'Schools→JRS→storyteller payments', owner: 'Me (Derek)', status: 'needs_you', rawStatus: 'needs your decision', description: 'Payment-flow map drafted; banking/contractor setup is owner-only.', dependency: 'Confirm take rate + payout tool + background-check standard', lastUpdated: '2026-06-04' },
  { taskNum: '44', company: 'JRS', title: 'Storyteller nurture campaign', owner: 'Agent M42', status: 'blocked', rawStatus: 'blocked on credential', description: 'Nurture flow drafted; blocked on the Wix→GoHighLevel field-name map.', dependency: 'Wix→GHL field map (credential)', lastUpdated: '2026-06-04' },
  { taskNum: '46', company: 'JRS', title: 'LinkedIn storyteller sourcing', owner: 'Me (Derek)', status: 'needs_you', rawStatus: 'needs your input', description: '5-message flow + tracker drafted; sent from your personal account.', dependency: 'Service region + pay range per engagement', lastUpdated: '2026-06-04' },
  { taskNum: '47', company: 'JRS', title: 'Webinar with Jason', owner: 'Jason', status: 'needs_you', rawStatus: 'needs date', description: 'Webinar kit drafted (invite, reminders, signup plan).', dependency: 'Jason picks date/time + registration link', lastUpdated: '2026-06-04' },
  { taskNum: '49', company: 'JRS', title: 'Books on TikTok Shop + Amazon', owner: 'Me (Derek)', status: 'needs_you', rawStatus: 'needs owner action', description: 'Listing kits drafted; account/ID/bank verification are owner-only.', dependency: 'Create seller accounts + verify identity/bank', lastUpdated: '2026-06-04' },
]

const BRIGHTLY: Task[] = [
  { taskNum: '13', company: 'Brightly', title: 'Confirm website ready to convert', owner: 'Me (Derek)', status: 'delivered_awaiting', rawStatus: 'awaiting price decision', description: 'Conversion-readiness audit drafted.', dependency: 'Pick ONE canonical Brightly price (gates the launch chain)', lastUpdated: '2026-06-24' },
  { taskNum: '15', company: 'Brightly', title: 'Final policies (Privacy/Terms/SMS)', owner: 'Claudio', status: 'done', rawStatus: 'done / needs legal review', deliverableSlackUrl: 'https://m42hqworkspace.slack.com/archives/D08BX46U6KZ', deliverableTitle: 'Legal pages live + fix walkthrough', description: 'Legal pages published; footer + slug fixes recorded.', dependency: 'Attorney review of ~11 flagged rows', lastUpdated: '2026-06-15' },
  { taskNum: '16', company: 'Brightly', title: 'Test signup / app / Airtable handoff', owner: 'Agent M42', status: 'in_progress', rawStatus: 'drafted', description: 'Launch QA test script drafted; runs once pricing settles.', dependency: 'Human click-through of the real payment test', lastUpdated: '2026-06-18' },
  { taskNum: '17', company: 'Brightly', title: 'Bank account + insurance', owner: 'Me (Derek)', status: 'needs_you', rawStatus: 'needs owner action', deliverableDriveUrl: 'https://drive.google.com/drive/u/0/folders/1fG7KrTq140U0W21b9eNLWoNwiBOV3mR5', deliverableTitle: 'LLC business filings (Articles, EIN)', description: 'Banking + insurance are owner-only; LLC filings in Drive.', dependency: 'Open bank account + insurance', lastUpdated: '2026-06-10' },
  { taskNum: '18', company: 'Brightly', title: 'Technician contractor agreement', owner: 'Me (Derek)', status: 'blocked', rawStatus: 'needs legal', description: 'Outline drafted; enforceable version needs an attorney.', dependency: 'Attorney to draft the signable version', lastUpdated: '2026-06-04' },
  { taskNum: '20', company: 'Brightly', title: 'Checkr background-check process', owner: 'Claudio', status: 'delivered_awaiting', rawStatus: 'awaiting vendor decision', description: 'Checkr research (steps, pricing, setup) ready.', dependency: 'Pick vendor route (direct vs via M42)', lastUpdated: '2026-06-18' },
  { taskNum: '22', company: 'Brightly', title: 'Amazon Associate page', owner: 'Me (Derek)', status: 'needs_you', rawStatus: 'needs account', description: 'Storefront copy + product research drafted.', dependency: 'Amazon Associate account + affiliate tag', lastUpdated: '2026-06-04' },
  { taskNum: '24', company: 'Brightly', title: 'NHWA certification', owner: 'Me (Derek)', status: 'in_progress', rawStatus: 'drafted', description: 'Requirements + deadlines tracked.', dependency: 'Owner enrollment decision', lastUpdated: '2026-06-04' },
  { taskNum: '30', company: 'Brightly', title: 'Vet referral partners', owner: 'Me (Derek)', status: 'needs_you', rawStatus: 'needs price list', deliverableSlackUrl: 'https://m42hqworkspace.slack.com/archives/D08BX46U6KZ', deliverableTitle: 'Referral kit + Scottsdale STR list', description: 'Outreach kit drafted; STR management-companies list on Slack.', dependency: 'Your pricing/numbers + confirm partner names', lastUpdated: '2026-06-11' },
  { taskNum: '32', company: 'Brightly', title: 'Contact service providers', owner: 'Agent M42', status: 'in_progress', rawStatus: 'gated', description: 'Scottsdale Licensed STR Registry — 3,008 leads pulled.', dependency: 'Depends on #30/#31 + price list', lastUpdated: '2026-06-11' },
]

export const DEMO_TASKS: Task[] = [...JRS, ...BRIGHTLY]
