import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";

export const PLUGIN_ID = "m42.plugin-agent-outputs";

const manifest: PaperclipPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: "0.1.0",
  displayName: "Agent Outputs",
  description: "Unified catalog of documents, comments, attachments and thread interactions generated by AI agents across all company issues.",
  author: "M42",
  categories: ["ui"],
  capabilities: [
    "api.routes.register",
    "database.namespace.read",
    "database.namespace.migrate",
    "companies.read",
    "projects.read",
    "issues.read",
    "issue.comments.read",
    "issue.documents.read",
    "agents.read",
    "ui.sidebar.register",
    "ui.page.register",
  ],
  entrypoints: {
    worker: "./dist/worker.js",
    ui: "./dist/ui",
  },
  database: {
    namespaceSlug: "agent_outputs",
    migrationsDir: "migrations",
    coreReadTables: [
      "companies",
      "projects",
      "agents",
      "issues",
      "issue_documents",
      "issue_comments",
      "issue_attachments",
      "documents",
      "assets",
      "issue_thread_interactions",
    ],
  },
  apiRoutes: [
    {
      routeKey: "list",
      method: "GET",
      path: "/outputs",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "detail",
      method: "GET",
      path: "/outputs/:kind/:id",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "filter-options",
      method: "GET",
      path: "/filter-options",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
  ],
  ui: {
    slots: [
      {
        type: "sidebar",
        id: "agent-outputs-sidebar",
        displayName: "Agent Outputs",
        exportName: "SidebarLink",
        order: 37,
      },
      {
        type: "page",
        id: "agent-outputs-page",
        displayName: "Agent Outputs",
        exportName: "OutputsPage",
        routePath: "outputs",
      },
    ],
  },
};

export default manifest;
